{
  "hash": "8dc162c97e0c4525e4c899738a48ed00",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Centro: moda, mediana y media\"\nsubtitle: \"Sesiones 12 y 13 · Análisis de Datos I\"\nauthor: \"CJJM\"\nlang: es\nformat:\n  revealjs:\n    theme: [default, ../../estilo-slides.scss]\n    slide-number: c/t\n    chalkboard: true\n    footer: \"[⌂ Inicio](../../index.html) · Análisis de Datos I · Sesiones 12 y 13 · Programa 2.2.1 y 2.2.2\"\n    incremental: false\n    fig-align: center\n    fig-width: 9\n    fig-height: 4\n    code-line-numbers: false\n    highlight-style: github\n    transition: fade\n    background-transition: fade\n    title-slide-attributes:\n      data-background-image: ../img/portada-graficas.png\n      data-background-size: cover\n      data-background-opacity: \"0.9\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n## El cuaderno de hoy {.smaller}\n\n**[Abrir en Colab](https://colab.research.google.com/github/cjjmdata/analisis_datos_i/blob/main/cuadernos/s12_centro.ipynb)**\n\nEntorno de ejecución → Cambiar tipo de entorno de ejecución → **R**, y después\nArchivo → Guardar una copia en Drive.\n\n## Objetivos de la sesión {.smaller}\n\nAl terminar esta sesión vas a poder:\n\n1. **Calcular** la moda, la mediana y la media de una variable, a mano y con R.\n2. **Distinguir** cuál de las tres describe mejor un conjunto, según su forma.\n3. **Calcular** una media ponderada y **justificar** qué pesa cada observación.\n4. **Explicar** por qué el promedio de una encuesta no es el promedio del país.\n\n::: {style=\"font-size:0.6em; color:#6C7A7B;\"}\nPrograma MAT1409 · 2.2.1 Moda y mediana · 2.2.2 Media aritmética simple y ponderada\n:::\n\n# Una base nueva {background-color=\"#24494C\"}\n\n## Los hogares de México {.smaller}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 91,414\nColumns: 15\n$ entidad     <chr> \"Aguascalientes\", \"Aguascalientes\", \"Aguascalientes\", \"Agu…\n$ tam_loc     <chr> \"100 mil y más\", \"100 mil y más\", \"100 mil y más\", \"100 mi…\n$ est_socio   <chr> \"Medio alto\", \"Medio alto\", \"Medio alto\", \"Medio alto\", \"M…\n$ clase_hog   <chr> \"Nuclear\", \"Nuclear\", \"Nuclear\", \"Nuclear\", \"Nuclear\", \"Nu…\n$ sexo_jefe   <chr> \"Hombre\", \"Hombre\", \"Mujer\", \"Hombre\", \"Mujer\", \"Hombre\", …\n$ edad_jefe   <dbl> 32, 48, 60, 43, 29, 30, 28, 33, 48, 55, 50, 28, 23, 23, 75…\n$ educa_jefe  <chr> \"Secundaria completa\", \"Profesional incompleta\", \"Secundar…\n$ integrantes <dbl> 4, 4, 2, 4, 4, 4, 4, 4, 3, 4, 3, 3, 2, 2, 2, 4, 4, 3, 5, 3…\n$ perceptores <dbl> 2, 2, 2, 3, 2, 3, 2, 1, 1, 2, 2, 2, 1, 1, 0, 4, 2, 2, 3, 1…\n$ ingreso     <dbl> 138232, 118014, 46866, 110430, 99494, 119559, 78831, 41395…\n$ gasto       <dbl> 47479, 38783, 28601, 43510, 132552, 74443, 35897, 148493, …\n$ alimentos   <dbl> 17858, 22384, 9383, 23683, 39207, 25007, 19286, 19903, 127…\n$ transporte  <dbl> 9929, 8797, 11009, 7069, 8297, 12315, 3781, 81814, 4544, 1…\n$ remesas     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 978, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ factor      <dbl> 207, 207, 207, 207, 196, 196, 196, 196, 196, 213, 213, 213…\n```\n\n\n:::\n:::\n\n\n::: {style=\"font-size:0.6em; color:#6C7A7B;\"}\nINEGI, Encuesta Nacional de Ingresos y Gastos de los Hogares 2024. El ingreso y\nel gasto son trimestrales, en pesos.\n:::\n\n## Las cuatro preguntas {.smaller}\n\n| Pregunta | Respuesta |\n|---|---|\n| Unidad de observación | **El hogar**, no la persona |\n| Variables | Ingreso y gasto en pesos, integrantes y perceptores en personas, el resto categóricas |\n| ¿Hubo aleatorización? | Sí, es una muestra probabilística de hogares |\n| ¿Observacional o experimento? | Observacional: nadie asignó a nadie |\n\n::: {.nota}\nCada renglón es un hogar. Un hogar de cinco personas y uno de una persona pesan\nigual en esta tabla, y eso va a importar hoy.\n:::\n\n## Tu apuesta {.smaller}\n\n::: {.friccion}\nUn hogar típico en México, **¿cuánto recibe al mes**?\n\nEscríbelo antes de ver nada. Un solo número.\n:::\n\n. . .\n\n\n::: {.cell}\n\n:::\n\n\nHay tres respuestas correctas y distintas, y la sesión es sobre por qué:\n\n| | Al mes |\n|---|---:|\n| El ingreso de en medio | **18,555** |\n| El promedio de la muestra | **24,091** |\n| El promedio del país | **25,955** |\n\n# La moda {background-color=\"#24494C\"}\n\n## El valor que más se repite {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(hogares, educa_jefe, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 2\n   educa_jefe                  n\n   <chr>                   <int>\n 1 Secundaria completa     24884\n 2 Primaria completa       14898\n 3 Primaria incompleta     12897\n 4 Preparatoria completa   12709\n 5 Profesional completa    10172\n 6 Sin instrucción          5416\n 7 Profesional incompleta   2907\n 8 Preparatoria incompleta  2802\n 9 Secundaria incompleta    2676\n10 Posgrado                 2026\n11 Preescolar                 27\n```\n\n\n:::\n:::\n\n\n::: {.nota}\nLa moda es la única medida de centro que funciona con variables **categóricas**:\n\"Secundaria completa\" no se puede promediar ni ordenar en una recta numérica.\n:::\n\n## La moda del ingreso {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\n::: {.friccion}\nCon 91,414 hogares, ¿cuántos crees que coinciden exactamente en\nel mismo ingreso?\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(table(hogares$ingreso), decreasing = TRUE)[1:3]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n20705 41024 20512 \n   30    28    27 \n```\n\n\n:::\n:::\n\n\n::: {.no-dice}\nEl ingreso toma **60,883 valores distintos** en\n91,414 hogares. El más repetido lo comparten\n**30 hogares**, el 0.033% de la muestra.\n\nCon variables continuas la moda describe una coincidencia, no un centro. Para\nel ingreso sirven las otras dos.\n:::\n\n# La mediana {background-color=\"#24494C\"}\n\n## Ya la calcularon {.smaller}\n\nLa mediana parte los datos ordenados en dos mitades. Es el segundo cuartil de la\nsesión 10, con otro nombre:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(hogares$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55666\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(hogares$ingreso, 0.50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  50% \n55666 \n```\n\n\n:::\n:::\n\n\n. . .\n\n::: {.nota}\nComo cuantil, la mediana responde **dónde corta**. Como medida de centro,\nresponde **cuánto recibe el hogar de en medio**. Es el mismo número con dos\npreguntas distintas detrás.\n:::\n\n## Lo que la mediana ignora {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\n::: {.friccion}\nSi el 1% de hogares con más ingreso saliera de la base, ¿qué le pasaría a la\nmediana?\n:::\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquitados <- filter(hogares, ingreso <= quantile(ingreso, 0.99))\n\nnrow(hogares) - nrow(quitados)      # hogares que salieron\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 915\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(hogares$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55666\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(quitados$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55190\n```\n\n\n:::\n:::\n\n\nLa mediana baja\n0.9%\ndespués de quitar 915 hogares. Se calcula\npor posición, y la posición casi no se mueve.\n\n# La media {background-color=\"#24494C\"}\n\n## Primero a mano {.smaller}\n\n::: {.a-mano}\nLa media aritmética suma todos los valores y reparte el total entre el número de\nobservaciones:\n\n$$\\bar{x} = \\frac{\\sum x_i}{n}$$\n\nEs el único de los tres centros que usa **todos** los datos. Por eso cada peso\nque entra o sale la mueve.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(hogares$ingreso) / length(hogares$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72273.59\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(hogares$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72273.59\n```\n\n\n:::\n:::\n\n\n## Media contra mediana {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](s12_centro_files/figure-revealjs/unnamed-chunk-10-1.png){width=864}\n:::\n:::\n\n\n::: {style=\"font-size:0.6em; color:#6C7A7B;\"}\nLa gráfica recorta el 5% de ingresos más altos para que se vea la forma. Los\n4,571 hogares recortados sí entran en los cálculos.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n::: {.nota}\nLa media queda **16,608 pesos** arriba de la mediana. La\ncola larga de la derecha jala el promedio, y la mediana se queda donde está la\nmayoría.\n:::\n\n## El dato que mueve el promedio {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(hogares$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72273.59\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(quitados$ingreso)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 67871.02\n```\n\n\n:::\n:::\n\n\n::: {.friccion}\nLa mediana bajó\n0.9%\ncon los mismos hogares fuera. **¿Por qué la media baja\n6.1%?**\n:::\n\n. . .\n\n::: {.no-dice}\n**64.7% de los hogares recibe menos que la media.**\n\nUn promedio describe el reparto total entre el número de hogares. Cuando la\ndistribución tiene cola larga, deja de describir al hogar que está en medio, y\ndos de cada tres quedan debajo de él.\n:::\n\n# La media ponderada {background-color=\"#24494C\"}\n\n## Una encuesta no es el país {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\nLa ENIGH visitó 91,414 hogares para describir a los\n**38,830,230** que hay en México. Cada hogar visitado representa a\nmuchos otros, y el número de cuántos viene en la columna `factor`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(hogares$factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]    4 7127\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(hogares$factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 38830230\n```\n\n\n:::\n:::\n\n\n::: {.nota}\nUn hogar con factor 7127 representa a\n7,127 hogares del país. Contarlo igual que a uno con\nfactor 4 describe a la muestra, no a México.\n:::\n\n## Primero a mano {.smaller}\n\n::: {.a-mano}\nLa media ponderada multiplica cada valor por su peso, suma, y reparte entre la\nsuma de los pesos:\n\n$$\\bar{x}_w = \\frac{\\sum w_i \\, x_i}{\\sum w_i}$$\n\nCon todos los pesos iguales a 1, la fórmula se vuelve la media de siempre: el\ndenominador es $n$.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(hogares$factor * hogares$ingreso) / sum(hogares$factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77863.85\n```\n\n\n:::\n\n```{.r .cell-code}\nweighted.mean(hogares$ingreso, hogares$factor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 77863.85\n```\n\n\n:::\n:::\n\n\n## La diferencia que hace {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Cómo se calcula               | Trimestral| Mensual|\n|:-----------------------------|----------:|-------:|\n|Media simple de la muestra    |     72,274|  24,091|\n|Media ponderada por el factor |     77,864|  25,955|\n\n\n:::\n:::\n\n\n::: {.nota}\nLa cifra ponderada, **77,864 pesos trimestrales**, es la que publica\nel INEGI, y queda 7.7% arriba de la\nmedia simple.\n\n\n::: {.cell}\n\n:::\n\n\nEl factor promedio sube de **359** en el décimo de\nhogares con menor ingreso a **505** en el de mayor.\nCada hogar de ingreso alto representa a más hogares que uno de ingreso bajo, y\nponderar sube el resultado.\n:::\n\n## El mismo cálculo, otra base {.smaller}\n\n\n::: {.cell}\n\n:::\n\n\n::: {.friccion}\nEl PIB per cápita promedio de estos 15 países, ¿se calcula\nsumándolos y dividiendo entre 15?\n:::\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Cómo se calcula               | Dólares por persona|\n|:-----------------------------|-------------------:|\n|Media simple de los países    |              28,620|\n|Media ponderada por población |              18,659|\n\n\n:::\n:::\n\n\n::: {.no-dice}\nLa media simple trata igual a India que a\nCosta Rica, y **sobreestima\n53%**.\n\nEn la ENIGH la media simple subestimaba; aquí sobreestima. El peso no corrige\nsiempre hacia el mismo lado: corrige hacia lo que cada observación representa.\n:::\n\n# El perfil de Oaxaca {background-color=\"#24494C\"}\n\n## Oaxaca y el país {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Medida                     |    Oaxaca|   Nacional|\n|:--------------------------|---------:|----------:|\n|Hogares en la muestra      |     2,644|     91,414|\n|Hogares que representa     | 1,212,520| 38,830,230|\n|Ingreso promedio ponderado |    52,025|     77,864|\n|Ingreso de en medio        |    34,868|     55,666|\n|Integrantes por hogar      |      3.52|       3.35|\n\n\n:::\n:::\n\n\n::: {.friccion}\nEl ingreso promedio de Oaxaca es el\n67% del\nnacional. **¿La mediana guarda la misma proporción?**\n:::\n\n## Las treinta y dos {.smaller}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](s12_centro_files/figure-revealjs/unnamed-chunk-21-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.nota}\nOaxaca ocupa el lugar **3 de 32** contando de menor a mayor. La línea\npunteada es el promedio nacional, que queda arriba de\n18 de las 32 entidades: el promedio del país\nlo sostienen unas pocas.\n:::\n\n## Qué medida usar {.smaller}\n\n| Si la variable es | Y la distribución | La medida que la describe |\n|---|---|---|\n| Categórica | cualquiera | **Moda** |\n| Numérica | simétrica | **Media** |\n| Numérica | con cola larga | **Mediana**, y la media al lado |\n| Numérica | de una muestra con factores | **Media ponderada** |\n\n::: {.no-dice}\nNinguna de las tres describe a un hogar en particular. El hogar de en medio\nrecibe 55,666 pesos al trimestre, y eso no dice cuántas personas\nviven de ese ingreso ni qué cuestan las cosas donde viven.\n\nEsa comparación, ingreso del hogar contra ingreso por persona, es la sesión 18.\n:::\n\n## Tarea {.smaller}\n\nSobre **tu serie del portafolio**:\n\n1. La media y la mediana de tu variable numérica, con sus unidades.\n2. Cuál de las dos describe mejor tu serie, con una razón que salga de la forma\n   de tu histograma.\n3. El porcentaje de tus observaciones que queda debajo de la media.\n4. Si tu base trae alguna columna que sirva de peso, la media ponderada y la\n   diferencia contra la simple. Si no la trae, escribe qué pesaría si pudieras.\n5. Una línea sobre lo que tu medida de centro no muestra.\n",
    "supporting": [
      "s12_centro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}